### ISSUE TITLE
Make it possible to generate k8s configurations separately from image assembly and deployment

### ISSUE THREAD

**Issue by batazor** [ServiceWeaver/weaver-kube#12]
I would like to use my own `Dockerfile` or have the option to pass my template instead of the default.

Accordingly, I would like to be able to use my own prebuilt pipeline to build services and be able to generate k8s-files as **an independent step**.

**Comment by rgrandl** [comment]
This work has been deprioritized, and we are currently focused primarily on addressing any critical issues.
