### ISSUE TITLE
Run clustered services like nats and minio 

### ISSUE THREAD

**Issue by gedw99** [ServiceWeaver/weaver-kube#29]
Weaver looks pretty cool 

Use case is I need a Cluster of nats Servers . Min of 3, as less than that messes up HA. 

Did not see a thing in examples for this use case.

—-

Then I need to run minio.
Again min of 3 and that needs persistent volume . Nothing like this in examples.

Now these 2 things have k8 operators but scale up and down differently.

nats scales with no config changes due to their real time gossip pattern for discovering each other. Nats gossips the the clients too ( like any golang micro service or golang App at the edge).

Not sure with minio. It has very precise numbering needs for the ip address and ports.

Then we have the running local scenarios. Nats can be embedded and so is just like any service. I saw your example code doing environment detected for local versus GKE versus AWS k8. So I guess I can use that detection code ? I guess that code will go into core weaver too so I can ask core what env I am on ? 

Pleae let’s me know your thoughts as I am really interested in this system 

The reason I am bring this up is because the business case is that devs can run on premise ( with no k8 at all ) as well as on cloud.

I think it’s a fair question to bring up .

**Comment by gedw99** [comment]
For on premise Nats and minio binaries can be embedded, with a service wrapper . Then the same thing can work on cloud too. 

Both just spit out the binary to disk and then get started up by the service manage for each.

Mir still does not solve scaling and config aspects though with weaver.

anyway just brainstorming options

**Comment by gedw99** [comment]
Btw does weaver work in windows on premise ?

**Comment by rgrandl** [comment]
Hi @gedw99, we will reply to your question shortly. Sorry about the delay.

**Comment by gedw99** [comment]
@rgrandl thanks - sorry about al the questions..

**Comment by rgrandl** [comment]
This work has been deprioritized, and we are currently focused primarily on addressing any critical issues.
