### ISSUE TITLE
Can allow custom dockerfile contents

### ISSUE THREAD

**Issue by Lvzhenqian** [ServiceWeaver/weaver-kube#30]
As the title says, 
I need to customize GOPROXY and other environment variables during the build process. 
To facilitate the download of dependent packages during the go build process..

Due to network reasons, I cannot download dependent packages and directly execute go install and go build..like this:
<img width="960" alt="image" src="https://github.com/ServiceWeaver/weaver-kube/assets/17487028/c92899bc-5a34-474d-948f-4cb0d80b56e1">

**Comment by spetrovic77** [comment]
Hi @Lvzhenqian, thanks for reporting this issue!

The reason we rebuild the weaver-kube binary is that the `weaver-kube` binary running on your non-Linux machine (I presume, MacOS?) will not run inside the container.

One option would be for us to provide our own set of base container images that include weaver-kube. Would that work for you, network-wise?

Providing other Dockerfile customization options is a more complicated issue and we're not ready to go there unless we really have to.

**Comment by Lvzhenqian** [comment]
@spetrovic77 Great, my network is difficult to download weaver-kube, using a base container images that includes weaver-kube can solve this problem

**Comment by rgrandl** [comment]
This work has been deprioritized, and we are currently focused primarily on addressing any critical issues.
