### ISSUE TITLE
Doesn't work with weaver v0.23.0

### ISSUE THREAD

**Issue by Multiply** [ServiceWeaver/weaver-kube#96]
The error message is correct in saying I use weaver v0.23.0 and weaver-kube v0.23.0, but isn't super helpful in telling me which version of weaver that is compatible with weaver-kube.
Reading the message I am assuming it's saying weaver-kube is built with weaver v0.23.0, but from the looks of the code, it's just printing out its own build version.

```
sample % go build .                                 
sample % weaver kube deploy config.yaml                                          

        ERROR: The binary you're trying to deploy ("sample") was built with
        github.com/ServiceWeaver/weaver module version v0.23.0. However, the 'weaver-kube'
        binary you're using was built with weaver module version v0.23.0. These versions are
        incompatible.

        We recommend updating both the weaver module your application is built with and
        updating the 'weaver-kube' command by running the following.

                go get github.com/ServiceWeaver/weaver@latest
                go install github.com/ServiceWeaver/weaver-kube/cmd/weaver-kube@latest

        Then, re-build your code and re-run 'weaver-kube deploy'. If the problem
        persists, please file an issue at https://github.com/ServiceWeaver/weaver/issues
exit status 1
```

Edit:
I think rewording the message, or reporting the actual dependency would help a bit:
https://github.com/ServiceWeaver/weaver-kube/blob/v0.23.0/go.mod#L6

**Comment by rgrandl** [comment]
@Multiply we updated the weaver kube to use the latest weaver version. So you shouldn't get that message anymore. 

We will fix the message as well. It is confusing.

**Comment by rgrandl** [comment]
@mwhittaker, thanks for fixing this. Could you fix the message for the GKE deployer as well?
